version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/New_York
  open-pull-requests-limit: 1
  reviewers:
  - theQuazz
  ignore:
  - dependency-name: aws-sdk
    versions:
    - "> 2.525.0, < 3"
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  rebase-strategy: disabled
